server:
  port: 8080
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver